ms_teams_live/models/attendee.py
from datetime import datetime

from ms_teams_live import db


class Attendee(db.Model):
    __tablename__ = "attendees"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    event_title = db.Column(db.String(100))
    name = db.Column(db.String(50))
    is_presenter = db.Column(db.Boolean)
    join_timestamp = db.Column(db.DateTime)
    left_timestamp = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, default=datetime.now())

    def __init__(
        self,
        event_title=None,
        name=None,
        is_presenter=None,
        join_timestamp=None,
        left_timestamp=None,
    ):
        self.event_title = event_title
        self.name = name
        self.is_presenter = is_presenter
        self.join_timestamp = join_timestamp
        self.left_timestamp = left_timestamp

ms_teams_live/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    app.config.from_object("ms_teams_live.config.DevelopmentConfig")
    db.init_app(app)

    from ms_teams_live.views.attendee import attendee

    app.register_blueprint(attendee)

    return app

ms_teams_live/views/attendee.py
import csv
import json
from datetime import datetime
from io import StringIO

import pandas as pd
from flask import Blueprint, make_response, redirect, render_template, request, url_for
from modules.application.read_attendee_report import ReadAttendeeReportService
from modules.model.attendee_report import AttendeeReport
from modules.pre_process import PreProcessorImpl
from ms_teams_live import db
from ms_teams_live.models.attendee import Attendee


def read_company_list():
    try:
        return json.load(open("company_domain.json", "r", encoding="utf-8"))
    except FileNotFoundError:
        print("company_domain.jsonを新規作成します")
        with open("company_domain.json", "w", encoding="utf-8") as f:
            f.write(json.dumps({}))
        return dict()


attendee = Blueprint("attendee", __name__)


@attendee.route("/", methods=["GET"])
def home():
    attendees = (
        Attendee.query.with_entities(Attendee.event_title)
        .distinct()
        .order_by(Attendee.event_title.desc())
    )
    return render_template("attendees/index.html", attendees=attendees)


@attendee.route("/attendees", methods=["POST"])
def add_attendee():
    company_domain = read_company_list()
    pre_processor = PreProcessorImpl(company_domain)
    read_report_service = ReadAttendeeReportService(pre_processor)

    ar = AttendeeReport(
        no=int((request.form["files"]).split("_")[0]),
        csv=pd.read_csv(StringIO(request.form["csv"]), encoding="utf_8_sig"),
    )
    results = read_report_service.execute([ar])

    for result in results:
        join_timestamp = datetime.strptime(
            " ".join([result[4], result[5]]), "%Y/%m/%d %H:%M:%S"
        )
        left_timestamp = datetime.strptime(
            " ".join([result[4], result[6]]), "%Y/%m/%d %H:%M:%S"
        )
        attendee = Attendee(
            event_title=request.form["title"],
            name=result[2],
            is_presenter=False,
            join_timestamp=join_timestamp,
            left_timestamp=left_timestamp,
        )
        db.session.add(attendee)
        db.session.commit()
    return redirect(url_for("attendee.home"))


@attendee.route("/attendees/new", methods=["GET"])
def new_attendee():
    return render_template("attendees/new.html")


@attendee.route("/attendees/<string:event_title>", methods=["GET"])
def show(event_title):
    attendees = Attendee.query.filter_by(event_title=event_title).all()
    return render_template(
        "attendees/show.html", title=event_title, attendees=attendees
    )


@attendee.route("/download/csv/attendees/<string:event_title>", methods=["GET"])
def download_csv(event_title):
    f = StringIO()
    writer = csv.writer(f, quotechar='"', quoting=csv.QUOTE_NONE, lineterminator="\n")

    writer.writerow(["氏名", "視聴開始", "視聴終了"])
    writer.writerows(
        [
            [a.name, a.join_timestamp, a.left_timestamp]
            for a in Attendee.query.filter_by(event_title=event_title).all()
        ]
    )

    response = make_response()
    response.data = f.getvalue()
    response.headers["Content-Type"] = "text/csv"
    response.headers["Content-Disposition"] = f"attachment; filename={event_title}.csv"
    return response

ms_teams_live/templates/attendees/index.html
{% extends "layout.html" %}

{% block body %}
<ul class="list-group list-group-flush">
    {% for attendee in attendees %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ attendee.event_title }}</h5>
            <a href="{{ url_for('attendee.show', event_title=attendee.event_title) }}" class="card-link">イベントの参加者</a>
            <a href="{{ url_for('attendee.download_csv', event_title=attendee.event_title) }}"
                class="card-link">csv出力</a>
        </div>
    </div>
    {% else %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">実施されたイベントはありません</h5>
        </div>
    </div>
    {% endfor %}
</ul>

{% endblock %}

ms_teams_live/templates/attendees/new.html
{% extends "layout.html" %}

{% block body %}
<form action="{{ url_for('attendee.add_attendee') }}" method=post class=add-attendee>
    <div class="form-group">
        <label for="InputTitle">イベントタイトル</label>
        <input type="text" class="form-control" id="title" name="title" />
    </div>
    <div class="form-group">
        <label for="InputTitle">出席者一覧ファイル</label>
        <input type="file" class="form-control" id="files" name="files" />
    </div>
    <div class="form-group">
        <label for="InputTitle">ファイルの内容</label>
        <textarea class="form-control" id="csv" name="csv"></textarea>
    </div>
    <button class="btn btn-primary" type="submit">登録</button>
</form>

<script>
    //選択したcsvファイルの中身を読み込み、textareaにセットする
    var input_files = document.getElementById("files");
    let reader = new FileReader();

    input_files.addEventListener('change', () => {
        for (row of input_files.files) {
            reader.readAsText(row, 'UTF-8');
            reader.onload = () => {
                document.getElementById("csv").value = reader.result;
            };
        }
    });
</script>

{% endblock %}

ms_teams_live/templates/attendees/show.html
{% extends "layout.html" %}
{% block body %}

<h1>{{ title }}</h1>

<table class="table">

    <thead>
        <tr>
            <th>氏名</th>
            <th>視聴開始</th>
            <th>視聴終了</th>
        </tr>
    </thead>

    <tbody>
        {% for attendee in attendees %}
        <tr>
            <td>{{ attendee.name }}</td>
            <td>{{ attendee.join_timestamp }}</td>
            <td>{{ attendee.left_timestamp }}</td>
        </tr>
        {% endfor %}
    </tbody>

</table>

{% endblock %}

ms_teams_live/templates/layout.html
<!DOCTYPE html>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet" type="text/css">

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('attendee.home') }}">出席者記録</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('attendee.new_attendee') }}">登録</a>
                </li>
            </ul>
        </div>
    </nav>

    {% for message in get_flashed_messages() %}
    <div class="alert alert-info" role="alert">
        {{ message }}
    </div>
    {% endfor %}

    <div class="body">
        {% block body %}{% endblock %}
    </div>

</div>